# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Prod environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsv2 #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 001
  location: eastus
  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: false
  enable_monitoring: true
  # feature store details
  enable_feature_store: true
  sql_admin_user: sqladmin
  sql_admin_password: ThisIsNotVerySecure!
  fs_onlinestore_conn_name: FEATHR-ONLINE-STORE-CONN
  feathr_app_image: feathrfeaturestore/feathr-registry
  feathr_app_image_tag: releases-v0.9.0
  react_enable_rbac: true
  aad_client_id: aca31809-3fa7-48a7-b29a-bd912e041602
  spark_version: 3.1
  priviledged_object_id: 5750d42c-a495-4c44-a257-0c45c384108c # AAD Object ID for user, used to set pividges for user in KV and Synapse for feature store components
  # added flag for this:  https://registry.terraform.io/providers/hashicorp/azurerm/2.99.0/docs/guides/3.0-app-service-beta
  # remove the environment variable when this is no longer required
  ARM_THREEPOINTZERO_BETA_RESOURCES: true

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Dev-rsmlopsado
  ado_service_connection_aml_ws: Azure-ARM-Dev-rsmlopsado

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 1.3.3
  terraform_workingdir: infrastructure
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
