# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

variables:
  - ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
      # 'main' branch: PRD environment
      - template: ../../config-infra-prod.yml
  - ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
      # 'develop' or feature branches: DEV environment
      - template: ../../config-infra-dev.yml

parameters:
  - name: jumphost_username
    type: string
    default: "azureuser"
  - name: jumphost_password
    type: string
    default: "ThisIsNotVerySecure!"
  - name: featurestore_sql_username
    type: string
    default: "sqladmin"
  - name: featurestore_sql_password
    type: string
    default: "ThisIsNotVerySecure!"
  - name: AAD_CLIENT_ID
    type: string
    default: "d5d082e1-641e-46a3-b681-81c885f355ab"
  - name: AZURE_TENANT_ID
    type: string
    default: "72f988bf-86f1-41af-91ab-2d7cd011db47"
  - name: AZURE_AAD_OBJECT_ID
    type: string
    default: "075c6b3e-1a26-44ff-9118-12cfd9fe75f8"

trigger:
  - none

pool:
  vmImage: $(ap_vm_image)

resources:
  repositories:
    - repository: mlops-templates
      name: Ritaja/mlops-templates
      endpoint: github-connection
      type: github
      ref: ft_featurestore #branch name

stages:
  - stage: CreateStorageAccountForTerraformState
    displayName: Create Storage for Terraform
    jobs:
      - job: CreateStorageForTerraform
        displayName: Create Storage for Terraform
        steps:
          - checkout: self
            path: s/
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/infra/create-resource-group.yml@mlops-templates
          - template: templates/infra/create-storage-account.yml@mlops-templates
          - template: templates/infra/create-storage-container.yml@mlops-templates
  - stage: DeployAzureMachineLearningRG
    displayName: Deploy AML Workspace
    jobs:
      - job: DeployAMLWorkspace
        displayName: Deploy Terraform
        steps:
          - checkout: self
            path: s/
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/infra/install-terraform.yml@mlops-templates
          - template: templates/infra/run-terraform-init.yml@mlops-templates
          - template: templates/infra/run-terraform-validate.yml@mlops-templates
          - template: templates/infra/run-terraform-plan.yml@mlops-templates
            parameters:
              jumphost_username: ${{parameters.jumphost_username}}
              jumphost_password: ${{parameters.jumphost_password}}
          - template: templates/infra/run-terraform-apply.yml@mlops-templates
            parameters:
              jumphost_username: ${{parameters.jumphost_username}}
              jumphost_password: ${{parameters.jumphost_password}}

  - stage: DeployFeatureStore
    displayName: Deploy Feature Store Components
    jobs:
      - job: DeployFeatureStoreResources
        displayName: Deploy Feature Store Resources
        steps:
          - checkout: self
            path: s/
          - checkout: mlops-templates
            path: s/templates/
          - template: templates/infra/create-featurestore.yml@mlops-templates
            parameters:
              featurestore_sql_username: ${{parameters.featurestore_sql_username}}
              featurestore_sql_password: ${{parameters.featurestore_sql_password}}
